### ISSUE TITLE
LLVM inconsistency error

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [scrt/avcleaner#1]
Hi,

i compiled the avcleaner successfully but get the following error everytime trying to use the binary:

`
CommandLine Error: Option 'non-global-value-max-name-size' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
`

Cmake Version 3.16.3
llvm Version 9.0.1

The winsdk paths are changed. Some idea how to get rid of this error?

Greetings

**Comment by plowsec** [comment]
Hi,

I've had this error last year actually. Unfortunately it is a pain to solve because there are a ton of reasons this could happen. The most likely is that you have several versions of LLVM installed on your system, and somehow both contribute to build the binary.

I recommend working inside a docker container, but if you find the solution to your problem, don't hesitate to share!

**Comment by S3cur3Th1sSh1t** [comment]
Hi,

Couldnt compile it in the docker container from your Dockerfile (llvm version is too new) and even tried it on newly installed linux systems with only one llvm version, no success so far.

Did you use the Docker container from the Dockerfile for compilation?

**Comment by plowsec** [comment]
Hi,

I haven't used the Dockerfile for a long time, and I see that since April 2020 clang is no longer built with BUILD_SHARED_LIBS=ON, which means we have to link against `libclang-cpp.so` instead of all the indivual libraries.

I will update the Dockerfile in time, but I managed to get it working again with the following steps:

```
docker build - -t avcleaner-deleteme
docker run -v ~/dev/scrt/avcleaner:/home/toto -it avcleaner-deleteme bash
sudo pacman -Syu
```

Edit CMakeList.txt as follows:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6723630..c35b981 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -28,25 +28,27 @@ include_directories(${LLVM_INCLUDE_DIRS})
 link_directories(${LLVM_LIBRARY_DIRS})
 add_definitions(${LLVM_DEFINITIONS})
 set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -Wno-unused-parameter -fno-strict-aliasing -fno-rtti -I/usr/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -L/usr/lib ")
-target_link_libraries(avcleaner.bin LLVM clangTooling clangToolingInclusions clangLex clangToolingCore clangAST clangASTMatchers clangBasic clangFrontend clangFrontendTool clangRewrite clangRewriteFrontend clangSerialization
-        LLVMX86AsmParser # MC, MCParser, Support, X86Desc, X86Info
-        LLVMX86Desc # MC, Support, X86AsmPrinter, X86Info
-        #LLVMX86AsmPrinter # MC, Support, X86Utils
-        LLVMX86Info # MC, Support, Target
-        LLVMX86Utils # Core, Support
-        LLVMipo
-        LLVMScalarOpts
-        LLVMInstCombine
-        LLVMTransformUtils
-        LLVMAnalysis
-        LLVMTarget
-        LLVMOption # Support
-        LLVMMCParser # MC, Support
-        LLVMMC # Object, Support
-        LLVMObject # BitReader, Core, Support
-        LLVMBitReader # Core, Support
-        LLVMCore # Support
-        LLVMSupport
+#target_link_libraries(avcleaner.bin LLVM clangTooling clangToolingInclusions clangLex clangToolingCore clangAST clangASTMatchers clangBasic clangFrontend clangFrontendTool clangRewrite clangRewriteFrontend clangSerialization
+
+target_link_libraries(avcleaner.bin LLVM clang-cpp
+       #LLVMX86AsmParser # MC, MCParser, Support, X86Desc, X86Info
+        #LLVMX86Desc # MC, Support, X86AsmPrinter, X86Info
+        ##LLVMX86AsmPrinter # MC, Support, X86Utils
+        #LLVMX86Info # MC, Support, Target
+        #LLVMX86Utils # Core, Support
+        #LLVMipo
+        #LLVMScalarOpts
+        #LLVMInstCombine
+        #LLVMTransformUtils
+        #LLVMAnalysis
+        #LLVMTarget
+        #LLVMOption # Support
+        #LLVMMCParser # MC, Support
+        #LLVMMC # Object, Support
+        #LLVMObject # BitReader, Core, Support
+        #LLVMBitReader # Core, Support
+        #LLVMCore # Support
+        #LLVMSupport
         stdc++
         )
```

and then (still inside the docker container):
```
rm -rf CMakeBuild
mkdir CMakeBuild && cd CMakeBuild
cmake ..
make -j 2
./avcleaner.bin --help
```

Then don't forget to update the path to the binary you just built in run_example.sh :P

Let me know if that helps!

**Comment by idrirap** [comment]
Hi!

It worked for me! Thanks for this fix.

But I am having issues with the windows.h file. I'm not sure I understood how I am supposed to use the winsdk.

**Comment by idrirap** [comment]
Never mind I figured out :)

**Comment by pussinboots1992** [comment]
@plowsec , could be a good idea to add ciopfs to the Dockerfile to facilitate things a bit to interface with winsdk header files...

**Comment by plowsec** [comment]
> @plowsec , could be a good idea to add ciopfs to the Dockerfile to facilitate things a bit to interface with winsdk header files...

Good idea, I will look into it.
