### ISSUE TITLE
Docker is on drugs

### ISSUE THREAD

**Issue by G1ft3dC0d3** [scrt/avcleaner#14]
All in screenshot
![image](https://user-images.githubusercontent.com/52042546/119065904-e6251400-b9de-11eb-9b7b-84ad451ec867.png)
![image](https://user-images.githubusercontent.com/52042546/119065834-b970fc80-b9de-11eb-841c-fbcaf83f0dcf.png)
![image](https://user-images.githubusercontent.com/52042546/119065880-d3124400-b9de-11eb-8edf-bdba89e07d26.png)

**Comment by plowsec** [comment]
Your docker is not on drugs :P

You should look into the option "-v" of docker, you must mount your local folder into the container if you want to grant it access.
