### ISSUE TITLE
Error running avcleaner

### ISSUE THREAD

**Issue by lepotekil** [scrt/avcleaner#19]
![image](https://user-images.githubusercontent.com/52042546/130869542-6afe6b9e-a646-48b2-9c5b-4d078229b82b.png)

**Comment by G1ft3dC0d3** [comment]
Same problem ^^

**Comment by T35R6braPwgDJKq** [comment]
youll have to provide the path to the `Windows.h` like

```
WININCLUDE='/mnt/windows/Include/10.0.17763.0'
avcleaner.bin $1  --strings=true --api=true --  \
-I $WININCLUDE/ucrt \
-I $WININCLUDE/shared \
-I $WININCLUDE/um \
-I $WININCLUDE/winrt \
```
The 10.0.17763.0 is the folder taken from windows sdk.
Otherwise you may also try `/usr/x86_64-w64-mingw32/include` or similar. Just `locate -r windows.h`

And youll have to `ln` the upper/lower case variants like `ln -s windows.h Windows.h`
