### ISSUE TITLE
docker install error 

### ISSUE THREAD

**Issue by WayZzz** [scrt/avcleaner#4]
==> Leaving fakeroot environment.
==> Finished making: yay 10.0.2-1 (Sat 18 Jul 2020 11:28:32 AM UTC)
error: '/tmp/yay/yay*.pkg.tar.xz': could not find or read package
loading packages...
The command '/bin/sh -c cd /tmp         && git clone https://aur.archlinux.org/yay.git  && cd yay       && chown -R toto. /tmp/yay/     && sudo -u toto makepkg -s         && pacman --noconfirm -U /tmp/yay/yay*.pkg.tar.xz' returned a non-zero code: 1

**Comment by plowsec** [comment]
Do you need `yay` ? If not, you can safely remove this dependency. In any case, I updated the Dockerfile.
