### ISSUE TITLE
Error in make -j 2

### ISSUE THREAD

**Issue by christiandgv** [scrt/avcleaner#7]
- Looking for os_signpost_interval_begin
-- Looking for os_signpost_interval_begin - not found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/toto/makes
[toto@e5914e876314 makes]$ make
Scanning dependencies of target avcleaner.bin
[ 16%] Building CXX object CMakeFiles/avcleaner.bin.dir/main.cpp.o
[ 33%] Building CXX object CMakeFiles/avcleaner.bin.dir/MatchHandler.cpp.o
[ 50%] Building CXX object CMakeFiles/avcleaner.bin.dir/Globals.cpp.o
[ 66%] Building CXX object CMakeFiles/avcleaner.bin.dir/ApiMatchHandler.cpp.o
[ 83%] Building CXX object CMakeFiles/avcleaner.bin.dir/Utils.cpp.o
[100%] Linking CXX executable avcleaner.bin
/usr/sbin/ld: cannot find -lclangTooling
/usr/sbin/ld: cannot find -lclangToolingInclusions
/usr/sbin/ld: cannot find -lclangLex
/usr/sbin/ld: cannot find -lclangToolingCore
/usr/sbin/ld: cannot find -lclangAST
/usr/sbin/ld: cannot find -lclangASTMatchers
/usr/sbin/ld: cannot find -lclangBasic
/usr/sbin/ld: cannot find -lclangFrontend
/usr/sbin/ld: cannot find -lclangFrontendTool
/usr/sbin/ld: cannot find -lclangRewrite
/usr/sbin/ld: cannot find -lclangRewriteFrontend
/usr/sbin/ld: cannot find -lclangSerialization
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/avcleaner.bin.dir/build.make:205: avcleaner.bin] Error 1
make[1]: *** [CMakeFiles/Makefile2:97: CMakeFiles/avcleaner.bin.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

**Comment by kanonufo** [comment]
It happens to me the same as you


Scanning dependencies of target avcleaner.bin
[ 16%] Building CXX object CMakeFiles/avcleaner.bin.dir/main.cpp.o
[ 33%] Building CXX object CMakeFiles/avcleaner.bin.dir/MatchHandler.cpp.o
[ 50%] Building CXX object CMakeFiles/avcleaner.bin.dir/Globals.cpp.o
[ 66%] Building CXX object CMakeFiles/avcleaner.bin.dir/ApiMatchHandler.cpp.o
[ 83%] Building CXX object CMakeFiles/avcleaner.bin.dir/Utils.cpp.o
[100%] Linking CXX executable avcleaner.bin
/usr/sbin/ld: cannot find -lclangTooling
/usr/sbin/ld: cannot find -lclangToolingInclusions
/usr/sbin/ld: cannot find -lclangLex
/usr/sbin/ld: cannot find -lclangToolingCore
/usr/sbin/ld: cannot find -lclangAST
/usr/sbin/ld: cannot find -lclangASTMatchers
/usr/sbin/ld: cannot find -lclangBasic
/usr/sbin/ld: cannot find -lclangFrontend
/usr/sbin/ld: cannot find -lclangFrontendTool
/usr/sbin/ld: cannot find -lclangRewrite
/usr/sbin/ld: cannot find -lclangRewriteFrontend
/usr/sbin/ld: cannot find -lclangSerialization
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/avcleaner.bin.dir/build.make:205: avcleaner.bin] Error 1
make[1]: *** [CMakeFiles/Makefile2:97: CMakeFiles/avcleaner.bin.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

**Comment by t3chn0t3s** [comment]
Greetings,

I'm experiencing a similar error.  My host OS is Ubuntu 20.04.1, running docker version 19.03.8.  The output I am given when executing "make -j 2" is shown below.

[toto@2ce036faf6ea CMakeBuild]$ make -j 2
Scanning dependencies of target avcleaner.bin
[ 33%] Building CXX object CMakeFiles/avcleaner.bin.dir/main.cpp.o
[ 33%] Building CXX object CMakeFiles/avcleaner.bin.dir/MatchHandler.cpp.o
[ 50%] Building CXX object CMakeFiles/avcleaner.bin.dir/Globals.cpp.o
[ 66%] Building CXX object CMakeFiles/avcleaner.bin.dir/ApiMatchHandler.cpp.o
[ 83%] Building CXX object CMakeFiles/avcleaner.bin.dir/Utils.cpp.o
[100%] Linking CXX executable avcleaner.bin
/usr/sbin/ld: cannot find -lclangTooling
/usr/sbin/ld: cannot find -lclangToolingInclusions
/usr/sbin/ld: cannot find -lclangLex
/usr/sbin/ld: cannot find -lclangToolingCore
/usr/sbin/ld: cannot find -lclangAST
/usr/sbin/ld: cannot find -lclangASTMatchers
/usr/sbin/ld: cannot find -lclangBasic
/usr/sbin/ld: cannot find -lclangFrontend
/usr/sbin/ld: cannot find -lclangFrontendTool
/usr/sbin/ld: cannot find -lclangRewrite
/usr/sbin/ld: cannot find -lclangRewriteFrontend
/usr/sbin/ld: cannot find -lclangSerialization
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/avcleaner.bin.dir/build.make:205: avcleaner.bin] Error 1
make[1]: *** [CMakeFiles/Makefile2:97: CMakeFiles/avcleaner.bin.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
[toto@2ce036faf6ea CMakeBuild]$ cat /etc/*releases
cat: '/etc/*releases': No such file or directory
[toto@2ce036faf6ea CMakeBuild]$ cat /etc/*release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux

**Comment by plowsec** [comment]
Yeah, if you're using the archlinux docker image to build avcleaner, obviously you have to use the CMakeLists_archlinux.txt instead on CMakeLists.txt. In any case, I renamed them because I feel I will have to answer tons of similar issues.
